name = "Soymilk"
author = "ghast"
version = "1.0.0b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91bef9594182ef4bc5df9c8bc37c2722f4ee0a6ffd5a0a01d650c7d300087e74"

[versions]
forge = "44.0.0"
minecraft = "1.19.2"
