name = "Cringemon"
author = "ghast"
version = "alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55e32739a91759e3870f52c49d2de7d15cc0b7aa9d5faf71d87e85f9ea6c5db0"

[versions]
minecraft = "1.19.2"
quilt = "0.18.6"
