name = "Cringemon"
author = "ghast"
version = "alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34fa28fba7f7ac5ab12a67dbc57026afee4c1e9a0d5d8f460f60dc80b07f3eb7"

[versions]
minecraft = "1.19.2"
quilt = "0.18.6"
