name = "Cringemon"
author = "ghast"
version = "alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2bedcc4313feaa58b7c368b0c5399d739a58c82730cdd415324a8720799c7a9"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"
