name = "Cringemon"
author = "ghast"
version = "alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9aae07dcd54cceb2d4b9dc32c3d594e31c79e31140d1368ad3c94225aa0d1bd7"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"
