name = "Cringemon"
author = "ghast"
version = "alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8187ee99908d1c048cf04b6d1db9f30e0f8bc363d63d3ce5986529b8c0de41e7"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"
