name = "Cringemon"
author = "ghast"
version = "alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcac48a1375887401101470bfce5d1db71f8e28d638e4defdb82b73cc8228046"

[versions]
minecraft = "1.19.2"
quilt = "0.18.6"
