name = "Cringemon"
author = "ghast"
version = "alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09619c9b868cabc1e370825fc3719bb626671e604d1b245e0e8b29e50d882daf"

[versions]
minecraft = "1.19.2"
quilt = "0.18.6"
