name = "Test Pack"
author = "ghast"
version = "1.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4de12388ec19e387f196e3fa43e8c55c9d568f9f31d9577a423af2b2339a86f0"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
